"""
Seed script to populate the database with sample scholarships and profiles.
Run `alembic upgrade head` before this script to ensure schema is up to date.
For fresh SQLite dev, Base.metadata.create_all is used as fallback.
"""
import json
from datetime import date
from app.db import SessionLocal, engine, Base
from app import models

# Ensure schema exists: use Alembic if available, else create_all for dev
try:
    from alembic import command
    from alembic.config import Config
    alembic_cfg = Config("alembic.ini")
    command.upgrade(alembic_cfg, "head")
except Exception:
    Base.metadata.create_all(bind=engine)

db = SessionLocal()

try:
    existing = db.query(models.Scholarship).first()
    if existing:
        print("Database already has data. Skipping seed.")
    else:
        scholarships = [
            # Government
            {
                "title": "CHED Merit Scholarship Program",
                "provider": "Commission on Higher Education (CHED)",
                "countries": ["Philippines"],
                "regions": [],
                "min_age": 16,
                "max_age": 25,
                "needs_tags": ["Financial Aid", "Merit-based"],
                "level": "College",
                "link": "https://ched.gov.ph/merit-scholarship",
                "description": "Merit-based scholarship for academically excellent students with financial needs.",
                "provider_type": "Government",
                "scholarship_type": "Merit-and-Need",
                "eligible_levels": ["College"],
                "eligible_regions": [],
                "eligible_cities": [],
                "residency_required": False,
                "eligible_school_types": ["Public", "Private"],
                "eligible_courses_psced": ["STEM", "Business", "Engineering", "Education", "Agriculture"],
                "max_income_threshold": 400000,
                "min_gwa_normalized": 90.0,
                "priority_groups": ["Underprivileged", "4Ps/Listahanan"],
                "benefit_tuition": True,
                "benefit_allowance_monthly": 3000,
                "benefit_books": True,
                "benefit_total_value": 80000,
                "required_documents": ["ITR", "BIRTH_CERT", "GOOD_MORAL", "TOR"],
                "has_qualifying_exam": True,
                "has_interview": True,
                "has_essay_requirement": True,
                "has_return_service": False,
                "application_deadline": date(2026, 6, 30),
                "application_open_date": date(2026, 3, 1),
                "academic_year_target": "2026-2027",
            },
            {
                "title": "DOST-SEI Undergraduate Scholarship",
                "provider": "Department of Science and Technology - SEI",
                "countries": ["Philippines"],
                "regions": [],
                "min_age": 17,
                "max_age": 22,
                "needs_tags": ["STEM", "Financial Aid", "Science", "Engineering"],
                "level": "College",
                "link": "https://ugs.science-scholarships.ph",
                "description": "STEM scholarship for Science, Technology, Engineering, and Mathematics courses.",
                "provider_type": "Government",
                "scholarship_type": "Merit-and-Need",
                "eligible_levels": ["College"],
                "eligible_regions": [],
                "eligible_cities": [],
                "residency_required": False,
                "eligible_school_types": ["Public", "Private"],
                "eligible_courses_psced": ["STEM", "Engineering"],
                "max_income_threshold": 400000,
                "min_gwa_normalized": 92.0,
                "priority_groups": ["Underprivileged"],
                "benefit_tuition": True,
                "benefit_allowance_monthly": 7000,
                "benefit_books": True,
                "benefit_total_value": 120000,
                "required_documents": ["ITR", "BIRTH_CERT", "GOOD_MORAL", "TOR"],
                "has_qualifying_exam": True,
                "has_interview": True,
                "has_essay_requirement": True,
                "has_return_service": True,
                "application_deadline": date(2026, 4, 15),
                "application_open_date": date(2026, 2, 1),
                "academic_year_target": "2026-2027",
            },
            {
                "title": "DOST-SEI Graduate Scholarship",
                "provider": "Department of Science and Technology - SEI",
                "countries": ["Philippines"],
                "regions": [],
                "min_age": 22,
                "max_age": 45,
                "needs_tags": ["STEM", "Financial Aid", "Graduate"],
                "level": "Graduate",
                "link": "https://science-scholarships.ph",
                "description": "Graduate scholarship for master's and doctoral programs in STEM.",
                "provider_type": "Government",
                "scholarship_type": "Merit-and-Need",
                "eligible_levels": ["Graduate"],
                "eligible_regions": [],
                "eligible_cities": [],
                "residency_required": False,
                "eligible_school_types": ["Public", "Private"],
                "eligible_courses_psced": ["STEM", "Engineering"],
                "max_income_threshold": 500000,
                "min_gwa_normalized": 88.0,
                "priority_groups": [],
                "benefit_tuition": True,
                "benefit_allowance_monthly": 15000,
                "benefit_books": True,
                "benefit_total_value": 200000,
                "required_documents": ["ITR", "BIRTH_CERT", "TOR", "ESSAY"],
                "has_qualifying_exam": True,
                "has_interview": True,
                "has_essay_requirement": True,
                "has_return_service": True,
                "application_deadline": date(2026, 5, 31),
                "application_open_date": date(2026, 3, 1),
                "academic_year_target": "2026-2027",
            },
            {
                "title": "TESDA Scholarship Program",
                "provider": "Technical Education and Skills Development Authority",
                "countries": ["Philippines"],
                "regions": [],
                "min_age": 15,
                "max_age": 60,
                "needs_tags": ["Vocational/TVET", "Financial Aid"],
                "level": "TVET",
                "link": "https://tesda.gov.ph",
                "description": "Technical-vocational education and training scholarships nationwide.",
                "provider_type": "Government",
                "scholarship_type": "Need",
                "eligible_levels": ["TVET"],
                "eligible_regions": [],
                "eligible_cities": [],
                "residency_required": False,
                "eligible_school_types": ["Public", "Private"],
                "eligible_courses_psced": ["STEM", "Agriculture", "Engineering"],
                "max_income_threshold": 500000,
                "min_gwa_normalized": 75.0,
                "priority_groups": ["Underprivileged", "4Ps/Listahanan"],
                "benefit_tuition": True,
                "benefit_allowance_monthly": 2000,
                "benefit_books": True,
                "benefit_total_value": 50000,
                "required_documents": ["BIRTH_CERT", "GOOD_MORAL", "FORM_137"],
                "has_qualifying_exam": False,
                "has_interview": True,
                "has_essay_requirement": False,
                "has_return_service": False,
                "application_deadline": date(2026, 12, 31),
                "application_open_date": date(2026, 1, 1),
                "academic_year_target": "2026-2027",
            },
            {
                "title": "CHED-Tulong Dulong Program",
                "provider": "Commission on Higher Education",
                "countries": ["Philippines"],
                "regions": [],
                "min_age": 16,
                "max_age": 30,
                "needs_tags": ["Financial Aid", "Underprivileged"],
                "level": "College",
                "link": "https://ched.gov.ph",
                "description": "Financial assistance for students from low-income families.",
                "provider_type": "Government",
                "scholarship_type": "Need",
                "eligible_levels": ["College"],
                "eligible_regions": [],
                "eligible_cities": [],
                "residency_required": False,
                "eligible_school_types": ["Public", "Private"],
                "eligible_courses_psced": ["STEM", "Business", "Engineering", "Education", "Agriculture"],
                "max_income_threshold": 400000,
                "min_gwa_normalized": 80.0,
                "priority_groups": ["Underprivileged", "4Ps/Listahanan"],
                "benefit_tuition": True,
                "benefit_allowance_monthly": 2500,
                "benefit_books": True,
                "benefit_total_value": 60000,
                "required_documents": ["ITR", "BIRTH_CERT", "GOOD_MORAL", "4PS_CERT"],
                "has_qualifying_exam": False,
                "has_interview": False,
                "has_essay_requirement": False,
                "has_return_service": False,
                "application_deadline": date(2026, 7, 31),
                "application_open_date": date(2026, 4, 1),
                "academic_year_target": "2026-2027",
            },
            {
                "title": "UniFAST Tertiary Education Subsidy",
                "provider": "Unified Student Financial Assistance System",
                "countries": ["Philippines"],
                "regions": [],
                "min_age": 16,
                "max_age": 35,
                "needs_tags": ["Financial Aid"],
                "level": "College",
                "link": "https://unifast.gov.ph",
                "description": "Tertiary education subsidy for eligible Filipino students.",
                "provider_type": "Government",
                "scholarship_type": "Need",
                "eligible_levels": ["College"],
                "eligible_regions": [],
                "eligible_cities": [],
                "residency_required": False,
                "eligible_school_types": ["Public", "Private"],
                "eligible_courses_psced": ["STEM", "Business", "Engineering", "Education", "Agriculture"],
                "max_income_threshold": None,  # Listahanan-based
                "min_gwa_normalized": 75.0,
                "priority_groups": ["4Ps/Listahanan"],
                "benefit_tuition": True,
                "benefit_allowance_monthly": 2000,
                "benefit_books": False,
                "benefit_total_value": 40000,
                "required_documents": ["ITR", "BIRTH_CERT", "4PS_CERT"],
                "has_qualifying_exam": False,
                "has_interview": False,
                "has_essay_requirement": False,
                "has_return_service": False,
                "application_deadline": date(2026, 8, 31),
                "application_open_date": date(2026, 5, 1),
                "academic_year_target": "2026-2027",
            },
            {
                "title": "GSIS Scholarship Program",
                "provider": "Government Service Insurance System",
                "countries": ["Philippines"],
                "regions": [],
                "min_age": 16,
                "max_age": 25,
                "needs_tags": ["GSIS Dependent", "Financial Aid"],
                "level": "College",
                "link": "https://gsis.gov.ph",
                "description": "Scholarship for children of GSIS members.",
                "provider_type": "Government",
                "scholarship_type": "Affiliation",
                "eligible_levels": ["College"],
                "eligible_regions": [],
                "eligible_cities": [],
                "residency_required": False,
                "eligible_school_types": ["Public", "Private"],
                "eligible_courses_psced": ["STEM", "Business", "Engineering", "Education"],
                "max_income_threshold": 500000,
                "min_gwa_normalized": 85.0,
                "priority_groups": [],
                "benefit_tuition": True,
                "benefit_allowance_monthly": 4000,
                "benefit_books": True,
                "benefit_total_value": 90000,
                "required_documents": ["ITR", "BIRTH_CERT", "GOOD_MORAL", "TOR"],
                "has_qualifying_exam": True,
                "has_interview": True,
                "has_essay_requirement": False,
                "has_return_service": False,
                "application_deadline": date(2026, 4, 30),
                "application_open_date": date(2026, 2, 1),
                "academic_year_target": "2026-2027",
            },
            {
                "title": "SSS Educational Loan Program",
                "provider": "Social Security System",
                "countries": ["Philippines"],
                "regions": [],
                "min_age": 16,
                "max_age": 30,
                "needs_tags": ["Financial Aid"],
                "level": "College",
                "link": "https://sss.gov.ph",
                "description": "Study now, pay later program for SSS members and dependents.",
                "provider_type": "Government",
                "scholarship_type": "Affiliation",
                "eligible_levels": ["College"],
                "eligible_regions": [],
                "eligible_cities": [],
                "residency_required": False,
                "eligible_school_types": ["Public", "Private"],
                "eligible_courses_psced": ["STEM", "Business", "Engineering", "Education"],
                "max_income_threshold": 500000,
                "min_gwa_normalized": 80.0,
                "priority_groups": [],
                "benefit_tuition": True,
                "benefit_allowance_monthly": 0,
                "benefit_books": False,
                "benefit_total_value": 80000,
                "required_documents": ["ITR", "BIRTH_CERT", "GOOD_MORAL", "TOR"],
                "has_qualifying_exam": False,
                "has_interview": True,
                "has_essay_requirement": False,
                "has_return_service": False,
                "application_deadline": date(2026, 6, 30),
                "application_open_date": date(2026, 3, 1),
                "academic_year_target": "2026-2027",
            },
            {
                "title": "OWWA Education and Training Program",
                "provider": "Overseas Workers Welfare Administration",
                "countries": ["Philippines"],
                "regions": [],
                "min_age": 16,
                "max_age": 30,
                "needs_tags": ["OFW Dependent", "Financial Aid"],
                "level": "College",
                "link": "https://owwa.gov.ph",
                "description": "Scholarship for dependents of OFWs.",
                "provider_type": "Government",
                "scholarship_type": "Affiliation",
                "eligible_levels": ["College"],
                "eligible_regions": [],
                "eligible_cities": [],
                "residency_required": False,
                "eligible_school_types": ["Public", "Private"],
                "eligible_courses_psced": ["STEM", "Business", "Engineering", "Education"],
                "max_income_threshold": 500000,
                "min_gwa_normalized": 85.0,
                "priority_groups": ["OFW Dependent"],
                "benefit_tuition": True,
                "benefit_allowance_monthly": 5000,
                "benefit_books": True,
                "benefit_total_value": 100000,
                "required_documents": ["ITR", "BIRTH_CERT", "OFW_DOCS", "GOOD_MORAL"],
                "has_qualifying_exam": True,
                "has_interview": True,
                "has_essay_requirement": True,
                "has_return_service": False,
                "application_deadline": date(2026, 5, 15),
                "application_open_date": date(2026, 2, 1),
                "academic_year_target": "2026-2027",
            },
            # Private Foundations
            {
                "title": "SM Foundation College Scholarship",
                "provider": "SM Foundation",
                "countries": ["Philippines"],
                "regions": [],
                "min_age": 16,
                "max_age": 28,
                "needs_tags": ["Financial Aid", "Underprivileged"],
                "level": "College",
                "link": "https://sm-foundation.org/scholarship",
                "description": "Educational assistance for financially challenged students with good academics.",
                "provider_type": "Private",
                "scholarship_type": "Need",
                "eligible_levels": ["College"],
                "eligible_regions": [],
                "eligible_cities": [],
                "residency_required": False,
                "eligible_school_types": ["Public", "Private"],
                "eligible_courses_psced": ["STEM", "Business", "Engineering", "Education"],
                "max_income_threshold": 250000,
                "min_gwa_normalized": 92.0,
                "priority_groups": ["Underprivileged", "4Ps/Listahanan"],
                "benefit_tuition": True,
                "benefit_allowance_monthly": 5000,
                "benefit_books": True,
                "benefit_total_value": 100000,
                "required_documents": ["ITR", "BIRTH_CERT", "SKETCH_HOME", "ESSAY"],
                "has_qualifying_exam": True,
                "has_interview": True,
                "has_essay_requirement": True,
                "has_return_service": False,
                "application_deadline": date(2026, 3, 31),
                "application_open_date": date(2026, 2, 1),
                "academic_year_target": "2026-2027",
            },
            {
                "title": "Ayala Foundation Scholarship Program",
                "provider": "Ayala Foundation",
                "countries": ["Philippines"],
                "regions": ["Metro Manila", "Luzon"],
                "min_age": 16,
                "max_age": 25,
                "needs_tags": ["Financial Aid", "Leadership"],
                "level": "College",
                "link": "https://ayalafoundation.org/scholarships",
                "description": "Scholarship for students with leadership potential and financial need.",
                "provider_type": "Private",
                "scholarship_type": "Merit-and-Need",
                "eligible_levels": ["College"],
                "eligible_regions": ["Metro Manila", "Luzon"],
                "eligible_cities": [],
                "residency_required": False,
                "eligible_school_types": ["Public", "Private"],
                "eligible_courses_psced": ["STEM", "Business", "Engineering", "Education"],
                "max_income_threshold": 400000,
                "min_gwa_normalized": 90.0,
                "priority_groups": [],
                "preferred_extracurriculars": ["Student Council", "Leadership"],
                "benefit_tuition": True,
                "benefit_allowance_monthly": 4000,
                "benefit_books": True,
                "benefit_total_value": 90000,
                "required_documents": ["ITR", "BIRTH_CERT", "GOOD_MORAL", "ESSAY"],
                "has_qualifying_exam": True,
                "has_interview": True,
                "has_essay_requirement": True,
                "has_return_service": False,
                "application_deadline": date(2026, 4, 30),
                "application_open_date": date(2026, 2, 15),
                "academic_year_target": "2026-2027",
            },
            {
                "title": "Gokongwei Brothers Foundation Scholarship",
                "provider": "Gokongwei Brothers Foundation",
                "countries": ["Philippines"],
                "regions": ["Metro Manila", "Luzon"],
                "min_age": 17,
                "max_age": 24,
                "needs_tags": ["STEM", "Engineering", "Financial Aid"],
                "level": "College",
                "link": "https://gokongweifoundation.org/scholarship",
                "description": "Engineering and technology scholarship for underprivileged students.",
                "provider_type": "Private",
                "scholarship_type": "Merit-and-Need",
                "eligible_levels": ["College"],
                "eligible_regions": ["Metro Manila", "Luzon"],
                "eligible_cities": [],
                "residency_required": False,
                "eligible_school_types": ["Public", "Private"],
                "eligible_courses_psced": ["STEM", "Engineering"],
                "max_income_threshold": 400000,
                "min_gwa_normalized": 92.0,
                "priority_groups": ["Underprivileged"],
                "benefit_tuition": True,
                "benefit_allowance_monthly": 5000,
                "benefit_books": True,
                "benefit_total_value": 100000,
                "required_documents": ["ITR", "BIRTH_CERT", "GOOD_MORAL", "TOR", "ESSAY"],
                "has_qualifying_exam": True,
                "has_interview": True,
                "has_essay_requirement": True,
                "has_return_service": False,
                "application_deadline": date(2026, 4, 15),
                "application_open_date": date(2026, 2, 1),
                "academic_year_target": "2026-2027",
            },
            {
                "title": "Metrobank Foundation Scholarship",
                "provider": "Metrobank Foundation",
                "countries": ["Philippines"],
                "regions": [],
                "min_age": 16,
                "max_age": 30,
                "needs_tags": ["Financial Aid", "Merit-based"],
                "level": "College",
                "link": "https://metrobank-foundation.org/scholarship",
                "description": "Scholarship for deserving students with excellent academic records.",
                "provider_type": "Private",
                "scholarship_type": "Merit-and-Need",
                "eligible_levels": ["College"],
                "eligible_regions": [],
                "eligible_cities": [],
                "residency_required": False,
                "eligible_school_types": ["Public", "Private"],
                "eligible_courses_psced": ["STEM", "Business", "Engineering", "Education"],
                "max_income_threshold": 400000,
                "min_gwa_normalized": 90.0,
                "priority_groups": [],
                "benefit_tuition": True,
                "benefit_allowance_monthly": 4000,
                "benefit_books": True,
                "benefit_total_value": 85000,
                "required_documents": ["ITR", "BIRTH_CERT", "GOOD_MORAL", "TOR"],
                "has_qualifying_exam": True,
                "has_interview": True,
                "has_essay_requirement": True,
                "has_return_service": False,
                "application_deadline": date(2026, 5, 31),
                "application_open_date": date(2026, 3, 1),
                "academic_year_target": "2026-2027",
            },
            {
                "title": "BPI Foundation Scholarship",
                "provider": "BPI Foundation",
                "countries": ["Philippines"],
                "regions": [],
                "min_age": 16,
                "max_age": 28,
                "needs_tags": ["Financial Aid", "Merit-based"],
                "level": "College",
                "link": "https://bpifoundation.org",
                "description": "College scholarship for academically gifted students.",
                "provider_type": "Private",
                "scholarship_type": "Merit-and-Need",
                "eligible_levels": ["College"],
                "eligible_regions": [],
                "eligible_cities": [],
                "residency_required": False,
                "eligible_school_types": ["Public", "Private"],
                "eligible_courses_psced": ["STEM", "Business", "Engineering", "Education"],
                "max_income_threshold": 400000,
                "min_gwa_normalized": 92.0,
                "priority_groups": [],
                "benefit_tuition": True,
                "benefit_allowance_monthly": 3500,
                "benefit_books": True,
                "benefit_total_value": 80000,
                "required_documents": ["ITR", "BIRTH_CERT", "GOOD_MORAL", "TOR"],
                "has_qualifying_exam": True,
                "has_interview": True,
                "has_essay_requirement": True,
                "has_return_service": False,
                "application_deadline": date(2026, 4, 30),
                "application_open_date": date(2026, 2, 1),
                "academic_year_target": "2026-2027",
            },
            {
                "title": "San Miguel Foundation Scholarship",
                "provider": "San Miguel Foundation",
                "countries": ["Philippines"],
                "regions": [],
                "min_age": 17,
                "max_age": 25,
                "needs_tags": ["Financial Aid", "Engineering", "Business"],
                "level": "College",
                "link": "https://sanmiguel.com.ph/foundation",
                "description": "Scholarship for engineering, business, and related fields.",
                "provider_type": "Private",
                "scholarship_type": "Merit-and-Need",
                "eligible_levels": ["College"],
                "eligible_regions": [],
                "eligible_cities": [],
                "residency_required": False,
                "eligible_school_types": ["Public", "Private"],
                "eligible_courses_psced": ["STEM", "Engineering", "Business"],
                "max_income_threshold": 400000,
                "min_gwa_normalized": 88.0,
                "priority_groups": [],
                "benefit_tuition": True,
                "benefit_allowance_monthly": 4000,
                "benefit_books": True,
                "benefit_total_value": 90000,
                "required_documents": ["ITR", "BIRTH_CERT", "GOOD_MORAL", "TOR"],
                "has_qualifying_exam": True,
                "has_interview": True,
                "has_essay_requirement": True,
                "has_return_service": False,
                "application_deadline": date(2026, 5, 15),
                "application_open_date": date(2026, 3, 1),
                "academic_year_target": "2026-2027",
            },
            {
                "title": "PLDT-Smart Foundation Scholarship",
                "provider": "PLDT-Smart Foundation",
                "countries": ["Philippines"],
                "regions": [],
                "min_age": 17,
                "max_age": 25,
                "needs_tags": ["IT", "STEM", "Financial Aid"],
                "level": "College",
                "link": "https://pldtsmartfoundation.org",
                "description": "Scholarship for IT and tech-related degree programs.",
                "provider_type": "Private",
                "scholarship_type": "Merit-and-Need",
                "eligible_levels": ["College"],
                "eligible_regions": [],
                "eligible_cities": [],
                "residency_required": False,
                "eligible_school_types": ["Public", "Private"],
                "eligible_courses_psced": ["STEM", "Engineering"],
                "max_income_threshold": 400000,
                "min_gwa_normalized": 90.0,
                "priority_groups": [],
                "benefit_tuition": True,
                "benefit_allowance_monthly": 5000,
                "benefit_books": True,
                "benefit_total_value": 100000,
                "required_documents": ["ITR", "BIRTH_CERT", "GOOD_MORAL", "TOR", "ESSAY"],
                "has_qualifying_exam": True,
                "has_interview": True,
                "has_essay_requirement": True,
                "has_return_service": False,
                "application_deadline": date(2026, 4, 30),
                "application_open_date": date(2026, 2, 15),
                "academic_year_target": "2026-2027",
            },
            # High School
            {
                "title": "DepEd SHS Voucher Program",
                "provider": "Department of Education",
                "countries": ["Philippines"],
                "regions": [],
                "min_age": 15,
                "max_age": 20,
                "needs_tags": ["Financial Aid"],
                "level": "High School",
                "link": "https://deped.gov.ph",
                "description": "Voucher program for senior high school students.",
                "provider_type": "Government",
                "scholarship_type": "Need",
                "eligible_levels": ["High School"],
                "eligible_regions": [],
                "eligible_cities": [],
                "residency_required": False,
                "eligible_school_types": ["Public", "Private"],
                "eligible_courses_psced": ["STEM", "Business", "Engineering", "Education", "Agriculture"],
                "max_income_threshold": 500000,
                "min_gwa_normalized": 75.0,
                "priority_groups": [],
                "benefit_tuition": True,
                "benefit_allowance_monthly": 0,
                "benefit_books": False,
                "benefit_total_value": 25000,
                "required_documents": ["BIRTH_CERT", "GOOD_MORAL", "FORM_137"],
                "has_qualifying_exam": False,
                "has_interview": False,
                "has_essay_requirement": False,
                "has_return_service": False,
                "application_deadline": date(2026, 6, 30),
                "application_open_date": date(2026, 3, 1),
                "academic_year_target": "2026-2027",
            },
            {
                "title": "Ateneo High School Financial Aid",
                "provider": "Ateneo de Manila University",
                "countries": ["Philippines"],
                "regions": ["Metro Manila"],
                "min_age": 12,
                "max_age": 18,
                "needs_tags": ["Financial Aid", "Merit-based"],
                "level": "High School",
                "link": "https://ateneo.edu",
                "description": "Need-based financial aid for high school students.",
                "provider_type": "Institutional",
                "scholarship_type": "Merit-and-Need",
                "eligible_levels": ["High School"],
                "eligible_regions": ["Metro Manila"],
                "eligible_cities": [],
                "residency_required": False,
                "eligible_school_types": ["Public", "Private"],
                "eligible_courses_psced": ["STEM", "Business", "Engineering", "Education", "Arts"],
                "max_income_threshold": 400000,
                "min_gwa_normalized": 90.0,
                "priority_groups": [],
                "benefit_tuition": True,
                "benefit_allowance_monthly": 0,
                "benefit_books": False,
                "benefit_total_value": 80000,
                "required_documents": ["ITR", "BIRTH_CERT", "GOOD_MORAL", "TOR"],
                "has_qualifying_exam": True,
                "has_interview": True,
                "has_essay_requirement": True,
                "has_return_service": False,
                "application_deadline": date(2026, 3, 31),
                "application_open_date": date(2026, 1, 15),
                "academic_year_target": "2026-2027",
            },
            # Graduate
            {
                "title": "CHED K-12 Transition Scholarship",
                "provider": "Commission on Higher Education",
                "countries": ["Philippines"],
                "regions": [],
                "min_age": 18,
                "max_age": 35,
                "needs_tags": ["Financial Aid", "Graduate"],
                "level": "Graduate",
                "link": "https://ched.gov.ph",
                "description": "Graduate scholarship for educators and professionals.",
                "provider_type": "Government",
                "scholarship_type": "Merit-and-Need",
                "eligible_levels": ["Graduate"],
                "eligible_regions": [],
                "eligible_cities": [],
                "residency_required": False,
                "eligible_school_types": ["Public", "Private"],
                "eligible_courses_psced": ["Education"],
                "max_income_threshold": 500000,
                "min_gwa_normalized": 85.0,
                "priority_groups": [],
                "benefit_tuition": True,
                "benefit_allowance_monthly": 8000,
                "benefit_books": True,
                "benefit_total_value": 120000,
                "required_documents": ["ITR", "BIRTH_CERT", "TOR", "ESSAY"],
                "has_qualifying_exam": True,
                "has_interview": True,
                "has_essay_requirement": True,
                "has_return_service": False,
                "application_deadline": date(2026, 6, 30),
                "application_open_date": date(2026, 3, 1),
                "academic_year_target": "2026-2027",
            },
            {
                "title": "ERC Graduate Fellowship",
                "provider": "Energy Regulatory Commission",
                "countries": ["Philippines"],
                "regions": ["Metro Manila"],
                "min_age": 22,
                "max_age": 40,
                "needs_tags": ["Engineering", "STEM", "Graduate"],
                "level": "Graduate",
                "link": "https://erc.gov.ph",
                "description": "Graduate fellowship for energy-related studies.",
                "provider_type": "Government",
                "scholarship_type": "Merit-and-Need",
                "eligible_levels": ["Graduate"],
                "eligible_regions": ["Metro Manila"],
                "eligible_cities": [],
                "residency_required": False,
                "eligible_school_types": ["Public", "Private"],
                "eligible_courses_psced": ["STEM", "Engineering"],
                "max_income_threshold": 500000,
                "min_gwa_normalized": 88.0,
                "priority_groups": [],
                "benefit_tuition": True,
                "benefit_allowance_monthly": 12000,
                "benefit_books": True,
                "benefit_total_value": 150000,
                "required_documents": ["ITR", "BIRTH_CERT", "TOR", "ESSAY"],
                "has_qualifying_exam": True,
                "has_interview": True,
                "has_essay_requirement": True,
                "has_return_service": False,
                "application_deadline": date(2026, 5, 15),
                "application_open_date": date(2026, 2, 1),
                "academic_year_target": "2026-2027",
            },
            # LGU / Sectoral
            {
                "title": "Pasig City Scholarship Program",
                "provider": "Pasig City LGU",
                "countries": ["Philippines"],
                "regions": ["Metro Manila"],
                "min_age": 16,
                "max_age": 30,
                "needs_tags": ["Financial Aid"],
                "level": "College",
                "link": "https://pasigcity.gov.ph",
                "description": "Local scholarship for Pasig City residents.",
                "provider_type": "LGU",
                "scholarship_type": "Need",
                "eligible_levels": ["College"],
                "eligible_regions": ["Metro Manila"],
                "eligible_cities": ["Pasig City"],
                "residency_required": True,
                "eligible_school_types": ["Public", "Private"],
                "eligible_courses_psced": ["STEM", "Business", "Engineering", "Education"],
                "max_income_threshold": 400000,
                "min_gwa_normalized": 85.0,
                "priority_groups": [],
                "benefit_tuition": True,
                "benefit_allowance_monthly": 3000,
                "benefit_books": True,
                "benefit_total_value": 70000,
                "required_documents": ["ITR", "BIRTH_CERT", "BARANGAY_CERT", "GOOD_MORAL"],
                "has_qualifying_exam": False,
                "has_interview": True,
                "has_essay_requirement": False,
                "has_return_service": False,
                "application_deadline": date(2026, 6, 30),
                "application_open_date": date(2026, 4, 1),
                "academic_year_target": "2026-2027",
            },
            {
                "title": "Quezon City Scholarship",
                "provider": "Quezon City LGU",
                "countries": ["Philippines"],
                "regions": ["Metro Manila"],
                "min_age": 16,
                "max_age": 35,
                "needs_tags": ["Financial Aid", "Merit-based"],
                "level": "College",
                "link": "https://quezoncity.gov.ph",
                "description": "Scholarship for QC residents pursuing higher education.",
                "provider_type": "LGU",
                "scholarship_type": "Merit-and-Need",
                "eligible_levels": ["College"],
                "eligible_regions": ["Metro Manila"],
                "eligible_cities": ["Quezon City"],
                "residency_required": True,
                "eligible_school_types": ["Public", "Private"],
                "eligible_courses_psced": ["STEM", "Business", "Engineering", "Education"],
                "max_income_threshold": 400000,
                "min_gwa_normalized": 88.0,
                "priority_groups": [],
                "benefit_tuition": True,
                "benefit_allowance_monthly": 3500,
                "benefit_books": True,
                "benefit_total_value": 75000,
                "required_documents": ["ITR", "BIRTH_CERT", "BARANGAY_CERT", "GOOD_MORAL"],
                "has_qualifying_exam": False,
                "has_interview": True,
                "has_essay_requirement": False,
                "has_return_service": False,
                "application_deadline": date(2026, 7, 31),
                "application_open_date": date(2026, 4, 1),
                "academic_year_target": "2026-2027",
            },
            {
                "title": "Philippine Normal University Scholarship",
                "provider": "Philippine Normal University",
                "countries": ["Philippines"],
                "regions": [],
                "min_age": 17,
                "max_age": 30,
                "needs_tags": ["Education", "Financial Aid"],
                "level": "College",
                "link": "https://pnu.edu.ph",
                "description": "Scholarship for future educators.",
                "provider_type": "Institutional",
                "scholarship_type": "Merit-and-Need",
                "eligible_levels": ["College"],
                "eligible_regions": [],
                "eligible_cities": [],
                "residency_required": False,
                "eligible_school_types": ["Public", "Private"],
                "eligible_courses_psced": ["Education"],
                "max_income_threshold": 400000,
                "min_gwa_normalized": 90.0,
                "priority_groups": [],
                "benefit_tuition": True,
                "benefit_allowance_monthly": 3000,
                "benefit_books": True,
                "benefit_total_value": 70000,
                "required_documents": ["ITR", "BIRTH_CERT", "GOOD_MORAL", "TOR"],
                "has_qualifying_exam": True,
                "has_interview": True,
                "has_essay_requirement": True,
                "has_return_service": False,
                "application_deadline": date(2026, 5, 31),
                "application_open_date": date(2026, 2, 1),
                "academic_year_target": "2026-2027",
            },
            {
                "title": "UP Presidential Scholarship",
                "provider": "University of the Philippines",
                "countries": ["Philippines"],
                "regions": [],
                "min_age": 16,
                "max_age": 25,
                "needs_tags": ["Merit-based", "Financial Aid"],
                "level": "College",
                "link": "https://up.edu.ph",
                "description": "Merit-based scholarship for top UPCAT passers.",
                "provider_type": "Institutional",
                "scholarship_type": "Merit-and-Need",
                "eligible_levels": ["College"],
                "eligible_regions": [],
                "eligible_cities": [],
                "residency_required": False,
                "eligible_school_types": ["Public", "Private"],
                "eligible_courses_psced": ["STEM", "Business", "Engineering", "Education", "Agriculture"],
                "max_income_threshold": 400000,
                "min_gwa_normalized": 95.0,
                "priority_groups": [],
                "benefit_tuition": True,
                "benefit_allowance_monthly": 6000,
                "benefit_books": True,
                "benefit_total_value": 120000,
                "required_documents": ["ITR", "BIRTH_CERT", "GOOD_MORAL", "TOR"],
                "has_qualifying_exam": True,
                "has_interview": True,
                "has_essay_requirement": True,
                "has_return_service": False,
                "application_deadline": date(2026, 4, 30),
                "application_open_date": date(2026, 2, 1),
                "academic_year_target": "2026-2027",
            },
        ]

        for s in scholarships:
            db.add(models.Scholarship(
                title=s["title"],
                provider=s["provider"],
                countries=",".join(s["countries"]),
                regions=",".join(s["regions"]),
                min_age=s["min_age"],
                max_age=s["max_age"],
                needs_tags=json.dumps(s["needs_tags"]),
                level=s.get("level"),
                link=s["link"],
                description=s["description"],
                provider_type=s.get("provider_type"),
                scholarship_type=s.get("scholarship_type"),
                eligible_levels=json.dumps(s.get("eligible_levels", [s.get("level")])),
                eligible_regions=json.dumps(s.get("eligible_regions", s["regions"])),
                eligible_cities=json.dumps(s.get("eligible_cities", [])),
                residency_required=s.get("residency_required", False),
                eligible_school_types=json.dumps(s.get("eligible_school_types", ["Public", "Private"])),
                eligible_courses_psced=json.dumps(s.get("eligible_courses_psced", [])),
                max_income_threshold=s.get("max_income_threshold"),
                min_gwa_normalized=s.get("min_gwa_normalized"),
                priority_groups=json.dumps(s.get("priority_groups", [])),
                preferred_extracurriculars=json.dumps(s.get("preferred_extracurriculars", [])),
                benefit_tuition=s.get("benefit_tuition", False),
                benefit_allowance_monthly=s.get("benefit_allowance_monthly"),
                benefit_books=s.get("benefit_books", False),
                benefit_total_value=s.get("benefit_total_value"),
                required_documents=json.dumps(s.get("required_documents", [])),
                has_qualifying_exam=s.get("has_qualifying_exam", False),
                has_interview=s.get("has_interview", False),
                has_essay_requirement=s.get("has_essay_requirement", False),
                has_return_service=s.get("has_return_service", False),
                application_deadline=s.get("application_deadline"),
                application_open_date=s.get("application_open_date"),
                academic_year_target=s.get("academic_year_target"),
                is_active=True,
            ))
        db.commit()
        print(f"Successfully seeded {len(scholarships)} scholarships!")

except Exception as e:
    print(f"Error seeding data: {e}")
    db.rollback()
    raise
finally:
    db.close()
