"""
Curated list of Philippine Higher Education Institutions (HEIs).
Used for autocomplete suggestions in the profile form.
"""

# Canonical list of schools - deduplicated, alphabetical
PHILIPPINE_SCHOOLS = sorted(set([
    "Adamson University",
    "Ateneo de Davao University",
    "Ateneo de Manila University",
    "Ateneo de Naga University",
    "Bicol University",
    "Bulacan State University",
    "Cagayan State University",
    "Central Luzon State University",
    "Central Philippine University",
    "Centro Escolar University",
    "De La Salle University",
    "De La Salle-College of Saint Benilde",
    "Don Mariano Marcos Memorial State University",
    "Far Eastern University",
    "Holy Angel University",
    "Ifugao State University",
    "Ilocos Sur Polytechnic State College",
    "Isabela State University",
    "Jose Rizal University",
    "La Consolacion College Manila",
    "La Salle University",
    "Lyceum of the Philippines University",
    "Mapua University",
    "Mariano Marcos State University",
    "Mindanao State University",
    "National University",
    "Negros Oriental State University",
    "Pamantasan ng Lungsod ng Maynila",
    "Pangasinan State University",
    "Philippine Normal University",
    "Polytechnic University of the Philippines",
    "Rizal Technological University",
    "San Beda University",
    "San Sebastian College-Recoletos",
    "Silliman University",
    "Southern Luzon State University",
    "St. Louis University",
    "St. Paul University Philippines",
    "Technological University of the Philippines",
    "University of Batangas",
    "University of Cebu",
    "University of Eastern Philippines",
    "University of Mindanao",
    "University of Negros Occidental-Recoletos",
    "University of Northern Philippines",
    "University of Perpetual Help System DALTA",
    "University of San Carlos",
    "University of Santo Tomas",
    "University of the Cordilleras",
    "University of the East",
    "University of the Philippines Baguio",
    "University of the Philippines Cebu",
    "University of the Philippines Diliman",
    "University of the Philippines Los Baños",
    "University of the Philippines Manila",
    "University of the Philippines Mindanao",
    "University of the Philippines Open University",
    "University of the Philippines Visayas",
    "University of the Philippines Tacloban",
    "University of the Philippines Baguio",
    "University of the Philippines Cebu",
    "Virgen Milagrosa University Foundation",
    "Visayas State University",
    "Western Mindanao State University",
    "Xavier University - Ateneo de Cagayan",
    "Adamson University",
    "Arellano University",
    "Asian Institute of Management",
    "Asian Institute of Maritime Studies",
    "Assumption College",
    "Ateneo de Zamboanga University",
    "Bataan Peninsula State University",
    "Batangas State University",
    "Benguet State University",
    "Cavite State University",
    "Central Bicol State University of Agriculture",
    "Central Mindanao University",
    "Colegio de San Juan de Letran",
    "Colegio de San Lorenzo",
    "Don Honorio Ventura State University",
    "Emilio Aguinaldo College",
    "Eulogio Amang Rodriguez Institute of Science and Technology",
    "Father Saturnino Urios University",
    "FEU Institute of Technology",
    "Filipino Academy of Cinematic Arts",
    "Holy Cross of Davao College",
    "International Academy of Management and Economics",
    "Jose Maria College",
    "Laguna State Polytechnic University",
    "Leyte Normal University",
    "Manuel L. Quezon University",
    "Marikina Polytechnic College",
    "Mindanao University of Science and Technology",
    "Miriam College",
    "New Era University",
    "Northwestern University",
    "Notre Dame of Marbel University",
    "Palawan State University",
    "Partido State University",
    "Philippine Christian University",
    "Philippine Women's University",
    "Ramon Magsaysay Memorial Colleges",
    "Saint Louis College",
    "Saint Mary's University",
    "San Pedro College",
    "Sorsogon State University",
    "Surigao del Norte State University",
    "Tarlac Agricultural University",
    "Tarlac State University",
    "Technological Institute of the Philippines",
    "University of Asia and the Pacific",
    "University of Makati",
    "University of Manila",
    "University of Nueva Caceres",
    "University of Pangasinan",
    "University of San Jose-Recoletos",
    "University of Science and Technology of Southern Philippines",
    "University of Southern Mindanao",
    "University of Southeastern Philippines",
    "University of the Assumption",
    "University of the Immaculate Conception",
    "University of the Philippines Iloilo",
    "University of the Philippines Visayas Tacloban College",
    "University of the Philippines Visayas Miag-ao",
    "University of the Philippines Visayas Iloilo City",
    "West Visayas State University",
    "Zamboanga State College of Marine Sciences and Technology",
]))
